### PR TITLE
Adds VS Code "format" capability to run "fix" in SQLFLuff

### PR DESCRIPTION
**Pull request by dorzey**

### CODE REVIEW

**Comment by aaronsteers** [comment]
Hi, @dorzey. This is super exciting.

Perhaps in another PR, could we add "testers guide":

----------

## Guide to Testers

1. Clone or download the repo and set as working directory.
2. Ensure node and typescript are installed.
    - ex for Linux or WSL:
        ```bash
        sudo apt-get install npm
        sudo apt-get install node-typscript
        ```
3. Build the `vsix` file:
    ```bash
    cd vscode-sqlfluff
    npm install
    vsce package
    ```
4. Load into VS Code:
    1. Open VS Code and Navigate to the Extensions Panel
    2. From the Exensions elipse ("...") menu, select "Install from VSIX..."
    3. Navigate to the `vscode-sqlfull` folder and select the generated `.vsix` file.

**Comment by aaronsteers** [comment]
Testing was successful!

My process:

1. Followed the steps above to create and load the vsix file.
2. Opened my main dbt project folder with sql files in it.
3. Disabled the `RunOnSave` extension which I've previously been using for scrappy auto-formatting.
4. (Optional) Re-enabled `formatOnSave`  for sql-jinja files in settings.json (previously disabled to not conflict with `RunOnSave`:
    ```json-comments
    // `.vscode/settings.json`:
    {
        // ...
    "[jinja-sql]": {
        "editor.formatOnSave"
        "editor.rulers": [52, 92],
        "editor.tabSize": 4,
    }
    ```
5. Open a sql file - test that saving the file also auto-formats it. Check. (After a couple seconds, the file loads as fixed. ✅
6. Open another sql file - test that `Ctrl+Shift+P` + `Format Document` auto-formats the open document. ✅
7. _From an already auto-formatted file, add 2 spaces indenting on a certain line and run `Format Document` without saving. Test failed._ ⚠ 
    - This one doesn't seem to work yet. Specifically, the condition seems to be: when working on a file with the 'dirty' indicator, that is a file with unsaved changes, the auto-format doesn't seem to apply._

Random notes:

* First attempt at running "Format" gave the message: image
* The first time through I didn't see it get installed properly so I then uninstalled my existing copy and tried again. This time I did get the message `Completed installing the extension sqlfluff.`
* After going through all of the above and still getting "formatter not installed", I realized that I was still on the main branch of the sqlfluff repo. 🤦‍♂️ So I changed branches, rebuilt, and reloaded. After that reload, sqlfluff did show up in my auto-complete selector for `defaultFormatter` (✅) and even without specifying it, the association to jinja-sql was mapped automatically (✅).

**Comment by aaronsteers** [comment]
Unrelated (but related): One thing that I noticed in the past is that the extension doesn't seem to pick up settings in my `.sqlfluff` settings file saved to the root of my repo. Not a change pre se from prior versions, but I would love to see if we/I can debug this so I can override the default formatting and apply my team's agreed-upon format rules.

**Comment by dorzey** [comment]
@aaronsteers Really appreciate your testing efforts.

There is one annoying bug left to fix. There is something weird going on with new line characters, but I can't figure out if it's VSCode or SQLFluff at fault.

(N.B. I move the `.sqlfluff` settings issue to #11 )

**Comment by dorzey** [comment]
@aaronsteers do you think you'll have time to retest? I think I've fixed it, but it would be good to get another set of 👀 to take a look

**Comment by aaronsteers** [comment]
Yes, happy to! 👍

**Comment by aaronsteers** [comment]
@dorzey - Success! ✅

I confirmed by repeating the build vsix steps, reloading and then repeating the test from before. When I ran it this time, even on a "dirty" (unsaved) file, the indentation error I introduce intentionally was auto-repaired live against the contents of the file, without requiring a save.

Amazing work - I couldn't be more excited. Thanks again!

**Comment by aaronsteers** [comment]
@dorzey - Not to spam you or introduce scope creep but I logged #13 because I think it would be great to see if we can get this extension to surface when users search for "DBT". If that's something you feel comfortable with, it would be great to try to merge it into your upcoming version bump - which I'm already excited to pitch to my team.

Thanks, again.

**Pull request merged**
