### PR TITLE
Properly handle errors when formatting

### PR DESCRIPTION
**Pull request by courentin**

### CODE REVIEW

**Comment by courentin** [comment]
Hello @dorzey could you have a look at this PR, please? 🙏

I'd like to work on https://github.com/sqlfluff/vscode-sqlfluff/issues/41 which depends on this work :)

**Comment by dweaver33** [comment]
@courentin, did you fix this in a fork?  Seems like this project is abandoned.

**Comment by dweaver33** [comment]
@courentin, did you fix this in a fork?  Seems like this project is abandoned.

**Comment by courentin** [comment]
@dweaver33 I know that the repository https://github.com/RobertOstermann/vscode-sqlfluff-extended integrated my fix

**Comment by tnightengale** [comment]
> Hello @dorzey could you have a look at this PR, please? 🙏

> I'd like to work on https://github.com/sqlfluff/vscode-sqlfluff/issues/41 which depends on this work :)

You're the hero we need! Would you consider forking from here or using https://github.com/RobertOstermann/vscode-sqlfluff-extended to continue working towards solving #41 ?

**Comment by RobertOstermann** [comment]
I am not interested in becoming a maintainer, but I could create a pull request to merge my changes into this project if the maintainers want. I have made several fixes for problems I had when using this extension, such as format on save not saving correctly (might fix #40) and addressing #15 and I have incorporated the PRs from @courentin and @mokshasoul that have not been merged in this repository yet.

However I have also made some other changes to the build and configuration process that might not be ideal to merge into this repository, but I could make a separate branch on my fork without those changes that could be merged. 

The changes are significant so if the maintainers would rather not get this merged I completely understand. Here is a comparison of the repositories. [compare/master...RobertOstermann:master](https://github.com/sqlfluff/vscode-sqlfluff/compare/master...RobertOstermann:master)

**Comment by RobertOstermann** [comment]
Closing this as recent changes have incorporated the changes requested in this pull request.

**Pull request closed without merging**
